### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'make_one_shot_iterator'

### ISSUE THREAD

**Issue by jiahuigeng** [bytedance/fedlearner#395]
When I follow the demo, here comes this error.
Even in the docker image.

**Comment by thomaszheng** [comment]
fedlearner/trainer/estimator.py

`
def _get_features_and_labels_from_input_fn(self, input_fn, mode):
       return input_fn(self._bridge, self._trainer_master)
`

**Comment by duanbing** [comment]
How about redirecting to #402 ?
