### ISSUE TITLE
quick_start里python命令缺失checkpoint_path参数和save-checkpoint-steps参数

### ISSUE THREAD

**Issue by DataAIPlayer** [bytedance/fedlearner#407]
添加这两个参数后才运行成功

**Comment by FruitTea2015** [comment]
请问可以具体说一下，应该怎样修改，修改成什么，才能运行成功吗？

**Comment by DataAIPlayer** [comment]
> 请问可以具体说一下，应该怎样修改，修改成什么，才能运行成功吗？

checkpoint_path参数可以是本地的一个路径，save-checkpoint-steps参数可以是一个整数

**Comment by duanbing** [comment]
Same issue as #402 .
