### ISSUE TITLE
What communication frameworks are used in this project?

### ISSUE THREAD

**Issue by tanjuntao** [bytedance/fedlearner#459]
When doing a Private Set Intersection or model training, we need to transmit intermediate values from one machine to another, so I want to know what communication frameworks (or communication tools) are used in this project?

I found there are many `.proto` files in `protocols/fedlearner/common` directory, and I also tried to search keyword `grpc` in this project and found  `import grpc` code snippet in some python file. So I wonder if `gRPC` is used in this project?

Looking forward to your reply.

**Comment by duanbing** [comment]
GRPC.  PSI channel set here https://github.com/bytedance/fedlearner/blob/master/fedlearner/data_join/rsa_psi/rsa_psi_signer.py#L125, and training here: https://github.com/bytedance/fedlearner/blob/master/fedlearner/trainer/bridge.py

**Comment by tanjuntao** [comment]
Thanks for your help!
