### ISSUE TITLE
No gRPC auto-generated files found?

### ISSUE THREAD

**Issue by tanjuntao** [bytedance/fedlearner#511]
Hi there, I found in some python files, the `*pb2.py` and `*pb2_grpc.py` generated by gRPC's `protoc` were imported, but I couldn't found where these auto-generated files are.

For example, in `fedlearner/data_join/rsa_psi/rsa_psi_signer.py` line 26-28:
``` python
from fedlearner.common import common_pb2 as common_pb
from fedlearner.common import data_join_service_pb2 as dj_pb
from fedlearner.common import data_join_service_pb2_grpc as dj_grpc
```
But I could not found any `*pb2.py` or `*pb2_grpc.py` in `fedlearner/common` directory. 

I also checked the content of `fedlearner/common/__init__.py`, it only imports `tensorflow_io`  in line 18:
``` python
import tensorflow_io
```

The same question also confuses me in another example. In `fedlearner/web_console_v2/api/fedlearner_webconsole/rpc/client.py` line 20-22:
``` python
from fedlearner_webconsole.proto import (
    service_pb2, service_pb2_grpc, common_pb2
)
```
I also couldn't find any auto-generated files in `fedlearner_webconsole.proto` package.

So, in one word, I am curious about where these auto-generated grpc-related files are located?

Your reply will be greatly appreciated!

**Comment by duanbing** [comment]
make protobuf

**Comment by tanjuntao** [comment]
Could you explain it in detail?

**Comment by duanbing** [comment]
it needs to be compiled before you run the example.

**Comment by duanbing** [comment]
请问问题解决了吗？Can we close this issue?  @tanjuntao

**Comment by tanjuntao** [comment]
Yes, we could close this issue. Thanks for you help.
