### ISSUE TITLE
Template fedlearner.k8s.io_flapps.yaml validation error?

### ISSUE THREAD

**Issue by chen1i** [bytedance/fedlearner#586]
Hi there,

I am a newbie to fedlearner and ran into error when executing following CLI
`
helm install fedlearner ./deploy/charts/fedlearner --namespace leader
`

> W0208 13:36:33.061422   40892 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0208 13:36:33.507972   40892 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0208 13:36:33.518213   40892 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0208 13:36:34.452027   40892 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0208 13:36:34.637682   40892 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: failed to create resource: CustomResourceDefinition.apiextensions.k8s.io "flapps.fedlearner.k8s.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[flReplicaSpecs].additionalProperties.properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[flReplicaSpecs].additionalProperties.properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]

I am using the latest code and K8S platform is using RKE 1.19.7, the fedlearner-stack is successfully deployed with no issue.
anything I missed?

Thanks in advance.

**Comment by peng09** [comment]
Hi, we add the deployment doc here: https://github.com/bytedance/fedlearner/pull/611/files. Please refer to this PR for details.

The error in your command should be caused by the K8S release version, please downgrade K8S to 1.16.9 version for deployment.

**Comment by chen1i** [comment]
thanks, I will give it a try.

**Comment by chen1i** [comment]
I managed to run the test after using ACK from aliyun. Thank you @peng09
