### ISSUE TITLE
fedlearner is supported horizontal and vertical multiple federated model?

### ISSUE THREAD

**Issue by anandes** [bytedance/fedlearner#706]
![62641cc0242aedd1aa2a7a39077b577f](https://user-images.githubusercontent.com/9313591/111946937-6d592700-8b17-11eb-9e6d-ae9c7ac70fd6.jpeg)
fedlearner support horizontal and vertical multiple federated model,  like left picture

if supported, how to implement.

**Comment by duanbing** [comment]
支持。 你可以介绍下你的具体场景。

**Comment by Guadaler** [comment]
明明可以中文交流沟通，为啥都在说英文？why？？
